export const HOME_ROUTE = '/'
export const ALL_MANGA_ROUTE = '/mangas'
export const ALL_ANIME_ROUTE = '/animes'
export const ALL_RANOBE_ROUTE = '/ranobe'
export const MANGA_ROUTE = '/mangas/:id'
export const ANIME_ROUTE = '/animes/:id'
export const RANOBE_ROUTE = '/ranobe/:id'
export const CHARACTER_ROUTE = '/characters/:id'
export const NEWS_ROUTE = '/news/:id'
export const PERSON_ROUTE = '/people/:id'
export const USER_ROUTE = '/users/:id'

export const API_BASE_URL = 'https://shikimori.one/api/'
export const API_IMAGE_URL = 'https://shikimori.one'